language: php

sudo: false

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'

script:
# Run your tests here.
- echo 'Tested'

deploy:
  provider: releases
  api_key:
    secure: "db64ffef9ecf2b8b0d0d0e011ffd256eae05844b"
  file: "test"
  skip_cleanup: true
  on:
      tags: true


