language: php

sudo: false

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'

script:
# Run your tests here.
- echo 'Tested'

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "artikus11"
      - git config --local user.email "artikus.sol@gmail.ru"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: "db64ffef9ecf2b8b0d0d0e011ffd256eae05844b"
  file: "latest"
  skip_cleanup: true
  on:
      tags: true

after_deploy: "release created"


